### PR TITLE
Fix issues with Carthage 

### LINKED ISSUE #11: CFBundleVersion is missing
After trying to upload to App Store Connect I got an error: The Info.plist is file is missing the required key: CFBundleVersion

### PR DESCRIPTION
**Pull request by fredyshox**
Added simple ruby script which modifies xcodeproj generated by swiftpm, so it has valid bundle identifier and build number. This caused issues with app distribution and on-device debugging.

Should resolve #11.

### CODE REVIEW

**Comment by fredyshox** [comment]
@freak4pc Also after this is accepted, could you publish updated framework binary with Swift 5.2 support?

File: Helpers/fix_project.rb [hunk 1]
```diff
@@ -0,0 +1,26 @@
+#!/usr/bin/env ruby
+
+require 'xcodeproj'
```
Comment (freak4pc) [inline Helpers/fix_project.rb:3]: You're missing a Gemile for this dependency

File: scripts/carthage-archive.sh [hunk 2]
```diff
@@ -24,7 +24,9 @@ if [ ! "$(printf '%s\n' "$REQUIRED_SWIFT_TOOLING" "$TOOLS_VERSION" | sort -V | h
 fi
 
 swift package generate-xcodeproj
```
Comment (freak4pc) [inline scripts/carthage-archive.sh:26]: I think it could be better to use something like 
```suggestion
swift package generate-xcodeproj --xcconfig-overrides Config.xcconfig
```

And having the configurations inside it, did you consider that/try that?

Comment (fredyshox) [reply scripts/carthage-archive.sh:26]: I like it! Didn't know SPM supports it. I'll give it a try

Comment (fredyshox) [reply scripts/carthage-archive.sh:26]: I tried using custom Config.xcconfig and have some issues. Initially I tried using something like that:
```
PRODUCT_BUNDLE_IDENTIFIER = com.CombineCommunity.$(PRODUCT_NAME)
CURRENT_PROJECT_VERSION = 1
```

The `CURRENT_PROJECT_VERSION` seems to work just fine, but `PRODUCT_BUNDLE_IDENTIFIER` has no effect. 
And it seems that, autogenerated xcodeproj is using my config on all targets (including dependencies), and I don’t see a way to control that other that manually inspecting the project.

I also tried defining some custom settings, like `BUNDLE_IDENTIFIER_PREFIX`, and then using them in Info.plist, but then I discovered that generated project is using a different one, stored in Project.xcodeproj/TargetName_Info.plist. `INFOPLIST_PATH` also has no effect.

**Comment by fredyshox** [comment]
UPDATE:

TIL Carthage supports xcconfig via `XCODE_XCCONFIG_FILE` environment variable. So I updated build script to use it. I've tested on-device app install and App Store Connect upload, and it works fine.

File: scripts/carthage-archive.sh [hunk 3]
```diff
@@ -17,14 +17,22 @@ fi
...
+    exit 1 
+fi
 
 if [ ! "$(printf '%s\n' "$REQUIRED_SWIFT_TOOLING" "$TOOLS_VERSION" | sort -V | head -n1)" = "$REQUIRED_SWIFT_TOOLING" ]; then
     echo 'You must have Swift Package Manager 5.1.0 or later.'
     exit 1
 fi
 
 swift package generate-xcodeproj
+export XCODE_XCCONFIG_FILE
```
Comment (freak4pc) [inline scripts/carthage-archive.sh:33]: cool trick!
